## Calculate the propogation matrix for the situations which need it

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import importlib
import xarray as xr
import os.path
import courtney
import scipy.optimize, scipy.signal
import cftime
import datetime
import scipy.linalg

import jemma_ODE_solvers3 as jde
import CAFE_tools2 as jcafe

In [3]:
def standardise(x):
    return (x-np.mean(x))/np.std(x)

In [4]:
indices = xr.load_dataset('saved_indices.nc')
indices.nino34_sst.data = standardise(indices.nino34_sst.data)
indices.wholeP_i20.data = standardise(indices.wholeP_i20.data)

## Parameter fit for the whole period with various spacial changes

In [4]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_STD',
                                 sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                        ensemble = range(97))

CPU times: user 9.03 s, sys: 159 ms, total: 9.19 s
Wall time: 5.21 s


(array([[[[-0.06258546,  0.14192735],
          [-0.16814919, -0.0071301 ]],
 
         [[-0.08025608,  0.1592996 ],
          [-0.16815062, -0.01869043]],
 
         [[-0.0931448 ,  0.17929092],
          [-0.20534456, -0.00791166]],
 
         [[-0.08539054,  0.13313043],
          [-0.19513584, -0.02033974]],
 
         [[-0.07435936,  0.14724289],
          [-0.17721532, -0.02624482]],
 
         [[-0.07255875,  0.15467052],
          [-0.16504041, -0.01709155]],
 
         [[-0.08114655,  0.12984531],
          [-0.17089171, -0.01344848]],
 
         [[-0.07281664,  0.14214866],
          [-0.17392825, -0.01958288]],
 
         [[-0.10534183,  0.15476265],
          [-0.19524312, -0.00604054]],
 
         [[-0.08139449,  0.15088484],
          [-0.17451429, -0.01831725]],
 
         [[-0.0668524 ,  0.1510709 ],
          [-0.1627644 , -0.03885742]],
 
         [[-0.08345388,  0.15249831],
          [-0.17214346, -0.01510039]],
 
         [[-0.07185857,  0.14889886],
          [-0.

## Different time windows

In [12]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_individual_year_STD',
                        sst_index = indices.nino34_sst,
                        i20_index = indices.wholeP_i20,
                        startyears = range(1965,2018),
                        windowlength = 1,
                                verbose = True)

[[-0.07273403  0.12881701]
 [-0.15990586 -0.02205835]]
Eigenvalues:[-0.04739619+0.14126779j -0.04739619-0.14126779j]
[[-0.09965202  0.12908299]
 [-0.16599498 -0.03946629]]
Eigenvalues:[-0.06955916+0.14325344j -0.06955916-0.14325344j]
Year 1965-1965, ensemble member slice(1, 97, None) finished
[-0.09965202  0.12908299 -0.16599498 -0.03946629]
----------------------------------------
[[-0.01911992  0.34759456]
 [-0.27612472 -0.00505488]]
Eigenvalues:[-0.0120874+0.30972567j -0.0120874-0.30972567j]
[[-0.06794876  0.33323813]
 [-0.29218333 -0.14163347]]
Eigenvalues:[-0.10479111+0.30985362j -0.10479111-0.30985362j]
Year 1966-1966, ensemble member slice(1, 97, None) finished
[-0.06794876  0.33323813 -0.29218333 -0.14163347]
----------------------------------------
[[ 0.03329653  0.05992539]
 [-0.11242299 -0.04653345]]
Eigenvalues:[-0.00661846+0.07172019j -0.00661846-0.07172019j]
[[-0.10173699 -0.05519071]
 [-0.22469603 -0.16552005]]
Eigenvalues:[-0.01779155+0.j -0.24946549+0.j]
Year 1967-1967

[[-0.13393522  0.10939657]
 [-0.30847212 -0.2520133 ]]
Eigenvalues:[-0.19297426+0.17395454j -0.19297426-0.17395454j]
Year 1989-1989, ensemble member slice(1, 97, None) finished
[-0.13393522  0.10939657 -0.30847212 -0.2520133 ]
----------------------------------------
[[-0.06912015  0.16120861]
 [-0.16670193  0.01708279]]
Eigenvalues:[-0.02601868+0.15816463j -0.02601868-0.15816463j]
[[-0.1621472   0.16232256]
 [-0.19143658 -0.03269722]]
Eigenvalues:[-0.09742221+0.16396692j -0.09742221-0.16396692j]
Year 1990-1990, ensemble member slice(1, 97, None) finished
[-0.1621472   0.16232256 -0.19143658 -0.03269722]
----------------------------------------
[[ 0.08873455  0.18538112]
 [ 0.0162132  -0.00598477]]
Eigenvalues:[ 0.11382182+0.j -0.03107204+0.j]
[[ 0.06615096  0.18666496]
 [ 0.04236015 -0.17209095]]
Eigenvalues:[ 0.09568046+0.j -0.20162045+0.j]
Year 1991-1991, ensemble member slice(1, 97, None) finished
[ 0.06615096  0.18666496  0.04236015 -0.17209095]
-----------------------------------

[[ 0.12397013  0.24821346]
 [-0.04261965  0.21577401]]
Eigenvalues:[0.16987207+0.09204228j 0.16987207-0.09204228j]
[[ 0.02918761 -0.15060103]
 [-0.16714557 -0.39288299]]
Eigenvalues:[ 0.0821754 +0.j -0.44587078+0.j]
Year 2015-2015, ensemble member slice(1, 97, None) finished
[ 0.02918761 -0.15060103 -0.16714557 -0.39288299]
----------------------------------------
[[-0.19912878  0.12412114]
 [-0.26153511  0.01774149]]
Eigenvalues:[-0.09069365+0.14388835j -0.09069365-0.14388835j]
[[-0.31659723  0.13752914]
 [-0.2489276   0.01046454]]
Eigenvalues:[-0.15306634+0.08655892j -0.15306634-0.08655892j]
Year 2016-2016, ensemble member slice(1, 97, None) finished
[-0.31659723  0.13752914 -0.2489276   0.01046454]
----------------------------------------
[[-0.02316885  0.01957675]
 [-0.27348777 -0.01370639]]
Eigenvalues:[-0.01843762+0.07301793j -0.01843762-0.07301793j]
[[-0.5300503   0.06585416]
 [-0.48737313 -0.0212115 ]]
Eigenvalues:[-0.45627886+0.j -0.09498294+0.j]
Year 2017-2017, ensemble membe

(array([[[[-0.09965202,  0.12908299],
          [-0.16599498, -0.03946629]]],
 
 
        [[[-0.06794876,  0.33323813],
          [-0.29218333, -0.14163347]]],
 
 
        [[[-0.10173699, -0.05519071],
          [-0.22469603, -0.16552005]]],
 
 
        [[[-0.11572645,  0.03653358],
          [-0.13506331, -0.01024283]]],
 
 
        [[[-0.11608599,  0.16066253],
          [-0.26645823, -0.16099162]]],
 
 
        [[[-0.26305375,  0.49905241],
          [-0.05724991,  0.01309669]]],
 
 
        [[[-0.05322319,  0.04189003],
          [-0.24553862, -0.26103298]]],
 
 
        [[[-0.04926353,  0.24296326],
          [-0.16268213,  0.02725102]]],
 
 
        [[[-0.15266785,  0.32299673],
          [-0.27808389,  0.06177819]]],
 
 
        [[[-0.12422342,  0.07295251],
          [-0.27856928, -0.08943145]]],
 
 
        [[[ 0.00505832,  0.04115824],
          [-0.20482279, -0.12396455]]],
 
 
        [[[-0.10003926,  0.15651258],
          [-0.19521809, -0.03093556]]],
 
 
        [[[-0.13

In [19]:
jcafe.fit_matrix_for_data_subset('fit_files/NINO3_SST__WHOLEPACIFIC_I20_1980_2002_STD', 
                        sst_index = indices.nino3_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = [1980], #Anything iterable
                            windowlength = 23, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

(array([[[[-4.80199476e-02,  1.60278431e-01],
          [-1.34252638e-01, -2.13211245e-03]],
 
         [[-7.82142556e-02,  1.83649736e-01],
          [-1.43859484e-01, -7.88947447e-03]],
 
         [[-9.01212618e-02,  1.92710178e-01],
          [-1.59483537e-01, -2.16370866e-02]],
 
         [[-9.58098607e-02,  1.61344981e-01],
          [-1.73811167e-01, -2.58028102e-03]],
 
         [[-7.21682852e-02,  1.82433968e-01],
          [-1.51842873e-01, -1.96527845e-02]],
 
         [[-7.42093794e-02,  2.00333096e-01],
          [-1.36710391e-01, -1.17319055e-02]],
 
         [[-7.41253278e-02,  1.65466088e-01],
          [-1.57689067e-01, -1.05022753e-02]],
 
         [[-7.62727406e-02,  1.82159024e-01],
          [-1.42744205e-01, -9.75110675e-03]],
 
         [[-1.05737644e-01,  1.74277079e-01],
          [-1.61583738e-01,  1.73595620e-03]],
 
         [[-8.55114530e-02,  1.93812167e-01],
          [-1.38032251e-01, -9.30858746e-03]],
 
         [[-8.07502915e-02,  1.72607120e-01],
    

In [18]:
jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_1980_2002_STD', 
                        sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = [1980], #Anything iterable
                            windowlength = 23, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

(array([[[[-0.04609506,  0.1465477 ],
          [-0.14126005,  0.00163203]],
 
         [[-0.06770396,  0.16871132],
          [-0.1559841 , -0.00154321]],
 
         [[-0.07276803,  0.16968974],
          [-0.1706715 , -0.01814768]],
 
         [[-0.07198497,  0.13437696],
          [-0.18093907, -0.0011865 ]],
 
         [[-0.05031256,  0.15291926],
          [-0.15243317, -0.02378281]],
 
         [[-0.06682717,  0.17444471],
          [-0.14363431, -0.00882835]],
 
         [[-0.06276441,  0.14225692],
          [-0.16228715, -0.00739161]],
 
         [[-0.06108948,  0.15805164],
          [-0.14632088, -0.00792661]],
 
         [[-0.0800206 ,  0.14645007],
          [-0.16334118, -0.00247225]],
 
         [[-0.0712209 ,  0.1683943 ],
          [-0.14634257, -0.00936312]],
 
         [[-0.06159428,  0.16168508],
          [-0.15094812, -0.01689226]],
 
         [[-0.05927181,  0.14877007],
          [-0.14631702, -0.01580779]],
 
         [[-0.05737388,  0.17010007],
          [-0.

In [13]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_sliding_decade_all_ensemble_STD', 
                        sst_index = indices.nino34_sst,
                        i20_index = indices.wholeP_i20,
                            startyears = range(1965,2010), #Anything iterable
                            windowlength = 10, #Inclusive
                            ensemble = [slice(1,97)], #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

CPU times: user 16.3 s, sys: 275 ms, total: 16.5 s
Wall time: 8.73 s


(array([[[[-0.058896  ,  0.14808284],
          [-0.18440751, -0.03958216]]],
 
 
        [[[-0.04928421,  0.14503001],
          [-0.18550683, -0.04550993]]],
 
 
        [[[-0.05200498,  0.13932743],
          [-0.17619377, -0.03880313]]],
 
 
        [[[-0.06577973,  0.15687162],
          [-0.18542253, -0.03178103]]],
 
 
        [[[-0.06749376,  0.18134803],
          [-0.18761533, -0.03439555]]],
 
 
        [[[-0.06728411,  0.18422419],
          [-0.18331873, -0.02881453]]],
 
 
        [[[-0.06197593,  0.17505155],
          [-0.20538146, -0.04181309]]],
 
 
        [[[-0.07389782,  0.18601278],
          [-0.21075526, -0.03023561]]],
 
 
        [[[-0.07126408,  0.18253004],
          [-0.20534237, -0.03416094]]],
 
 
        [[[-0.06369292,  0.15474781],
          [-0.20488347, -0.01355726]]],
 
 
        [[[-0.07460823,  0.16455821],
          [-0.18777665, -0.01305301]]],
 
 
        [[[-0.08651182,  0.17905256],
          [-0.18717278, -0.00996638]]],
 
 
        [[[-0.08

In [14]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_sliding_decade_each_ensemble_STD', 
                        sst_index = indices.nino34_sst,
                        i20_index = indices.wholeP_i20,
                            startyears = range(1965,2010), #Anything iterable
                            windowlength = 10, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                                )

CPU times: user 4min 37s, sys: 3.77 s, total: 4min 41s
Wall time: 2min 40s


(array([[[[-0.04656234,  0.14145793],
          [-0.18961503, -0.02926959]],
 
         [[-0.05256676,  0.13662617],
          [-0.15076802, -0.04523602]],
 
         [[-0.08233752,  0.19801083],
          [-0.2327783 ,  0.01381894]],
 
         ...,
 
         [[-0.08374821,  0.13572683],
          [-0.18609291, -0.02994718]],
 
         [[-0.03892191,  0.14791316],
          [-0.22203916, -0.04865344]],
 
         [[-0.0594323 ,  0.10223908],
          [-0.21648581, -0.04788799]]],
 
 
        [[[-0.03283044,  0.13534206],
          [-0.19065935, -0.03319493]],
 
         [[-0.05479346,  0.14209687],
          [-0.15187518, -0.0346163 ]],
 
         [[-0.07873403,  0.21542862],
          [-0.24856967,  0.00394478]],
 
         ...,
 
         [[-0.07057164,  0.15038686],
          [-0.18529862, -0.04420934]],
 
         [[-0.0261894 ,  0.1264865 ],
          [-0.22149254, -0.06719596]],
 
         [[-0.05742073,  0.11439667],
          [-0.23542849, -0.03978771]]],
 
 
        [[[-0.

In [6]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_sliding_15yr_each_ensemble_STD', 
                        sst_index = indices.nino34_sst,
                        i20_index = indices.wholeP_i20,
                            startyears = range(1965,2005), #Anything iterable
                            windowlength = 15, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                                )

CPU times: user 4min 5s, sys: 2.74 s, total: 4min 8s
Wall time: 2min 10s


(array([[[[-0.04474756,  0.1375362 ],
          [-0.19830003, -0.03603298]],
 
         [[-0.05462288,  0.14686914],
          [-0.15164575, -0.05357246]],
 
         [[-0.0905154 ,  0.20362225],
          [-0.23403031,  0.00638678]],
 
         ...,
 
         [[-0.08806587,  0.13533361],
          [-0.18696037, -0.03670249]],
 
         [[-0.03132203,  0.12684547],
          [-0.20387769, -0.0739222 ]],
 
         [[-0.06215041,  0.11937194],
          [-0.23830312, -0.04716078]]],
 
 
        [[[-0.039595  ,  0.14017386],
          [-0.2005362 , -0.03763946]],
 
         [[-0.0585059 ,  0.15476031],
          [-0.1573053 , -0.04641628]],
 
         [[-0.08672925,  0.21421266],
          [-0.24068717,  0.00129276]],
 
         ...,
 
         [[-0.0807389 ,  0.14877777],
          [-0.17966506, -0.04586819]],
 
         [[-0.03077304,  0.12173484],
          [-0.2045407 , -0.0817984 ]],
 
         [[-0.05848844,  0.12930273],
          [-0.24236703, -0.03646227]]],
 
 
        [[[-0.

## Seasonal fits

In [15]:
%%time
for s in ('DJF','MAM','JJA','SON'):
    jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_'+s+'_STD', 
                            sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = np.array((1965,)), #Anything iterable
                            windowlength = 2019-1965, #That's a subtraction deliberately 
                            ensemble = range(97), #also has to be iterable
                            season = s,
                                     verbose = False,
                           )

CPU times: user 27.5 s, sys: 365 ms, total: 27.9 s
Wall time: 15.6 s


In [16]:
#Seasonal fits for each year
for s in ('DJF','MAM','JJA','SON'):
    jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_yearly_'+s+'_STD', 
                            sst_index = indices.nino34_sst,
                            i20_index = indices.wholeP_i20,
                                startyears = range(1965,2019), #Anything iterable
                                windowlength = 1,
                                ensemble = [slice(1,97)], #also has to be iterable
                                season = s,
                                     verbose = True,
                               )

[[-0.18479683  0.0695107 ]
 [-0.56774296  0.05195202]]
Eigenvalues:[-0.0664224+0.15953591j -0.0664224-0.15953591j]
[[-0.2037572   0.07144338]
 [-0.50024946 -0.10353027]]
Eigenvalues:[-0.15364373+0.18228592j -0.15364373-0.18228592j]
Year 1965-1965, ensemble member slice(1, 97, None) finished
[-0.2037572   0.07144338 -0.50024946 -0.10353027]
----------------------------------------
[[-0.13453121 -0.00229321]
 [-0.23637381 -0.07035689]]
Eigenvalues:[-0.14208797+0.j -0.06280013+0.j]
[[-0.20251009 -0.09888444]
 [-0.32873354 -0.2276995 ]]
Eigenvalues:[-0.03436947+0.j -0.39584012+0.j]
Year 1966-1966, ensemble member slice(1, 97, None) finished
[-0.20251009 -0.09888444 -0.32873354 -0.2276995 ]
----------------------------------------
[[-0.1271889   0.06293142]
 [-0.25045596 -0.09820867]]
Eigenvalues:[-0.11269879+0.124706j -0.11269879-0.124706j]
[[-0.22142177 -0.00556812]
 [-0.424219   -0.23628112]]
Eigenvalues:[-0.17968537+0.j -0.27801753+0.j]
Year 1967-1967, ensemble member slice(1, 97, None)

Year 1988-1988, ensemble member slice(1, 97, None) finished
[-0.13055626  0.05964896 -0.32127517  0.25530361]
----------------------------------------
[[-0.0336601   0.22074444]
 [-0.25022339  0.07392829]]
Eigenvalues:[0.0201341+0.22878288j 0.0201341-0.22878288j]
[[-0.10476538  0.18246669]
 [-0.33865218 -0.00223855]]
Eigenvalues:[-0.05350196+0.24323817j -0.05350196-0.24323817j]
Year 1989-1989, ensemble member slice(1, 97, None) finished
[-0.10476538  0.18246669 -0.33865218 -0.00223855]
----------------------------------------
[[-0.05877268  0.27051565]
 [-0.28078906  0.12459678]]
Eigenvalues:[0.03291205+0.25990719j 0.03291205-0.25990719j]
[[-0.11277242  0.27306584]
 [-0.27683818  0.0350076 ]]
Eigenvalues:[-0.03888241+0.26483073j -0.03888241-0.26483073j]
Year 1990-1990, ensemble member slice(1, 97, None) finished
[-0.11277242  0.27306584 -0.27683818  0.0350076 ]
----------------------------------------
[[-0.0326988   0.36075142]
 [-0.21869234  0.41649914]]
Eigenvalues:[0.19190017+0.1686

[[-0.69442632  0.43337829]
 [-1.14419538  0.77446765]]
Eigenvalues:[-0.16864879+0.j  0.24869012+0.j]
[[-0.73266833  0.4374485 ]
 [-0.78356004  0.30868849]]
Eigenvalues:[-0.21198992+0.26769602j -0.21198992-0.26769602j]
Year 2011-2011, ensemble member slice(1, 97, None) finished
[-0.73266833  0.4374485  -0.78356004  0.30868849]
----------------------------------------
[[-0.13940815  0.26177623]
 [-0.79068009 -0.08124913]]
Eigenvalues:[-0.11032864+0.45402162j -0.11032864-0.45402162j]
[[-0.31121996  0.21740598]
 [-0.95001014 -0.1444928 ]]
Eigenvalues:[-0.22785638+0.44675318j -0.22785638-0.44675318j]
Year 2012-2012, ensemble member slice(1, 97, None) finished
[-0.31121996  0.21740598 -0.95001014 -0.1444928 ]
----------------------------------------
[[-0.13552984  0.08738987]
 [-0.49580782 -0.14270193]]
Eigenvalues:[-0.13911588+0.20812429j -0.13911588-0.20812429j]
[[-0.71641434 -0.14463793]
 [-1.17140053 -0.47530496]]
Eigenvalues:[-1.02476801+0.j -0.16695129+0.j]
Year 2013-2013, ensemble mem

[[-0.08464588  0.18470025]
 [-0.3557823  -0.38106087]]
Eigenvalues:[-0.23285337+0.20915932j -0.23285337-0.20915932j]
Year 1979-1979, ensemble member slice(1, 97, None) finished
[-0.08464588  0.18470025 -0.3557823  -0.38106087]
----------------------------------------
[[ 0.12429001  0.13256611]
 [-0.2513133  -0.02003074]]
Eigenvalues:[0.05212963+0.16765591j 0.05212963-0.16765591j]
[[ 0.01804396  0.07052918]
 [-0.37646535 -0.17060134]]
Eigenvalues:[-0.07627869+0.13287223j -0.07627869-0.13287223j]
Year 1980-1980, ensemble member slice(1, 97, None) finished
[ 0.01804396  0.07052918 -0.37646535 -0.17060134]
----------------------------------------
[[-0.0948537   0.26093581]
 [-0.20802725  0.04986355]]
Eigenvalues:[-0.02249507+0.22146329j -0.02249507-0.22146329j]
[[-0.16591687  0.24248653]
 [-0.2433008  -0.0642193 ]]
Eigenvalues:[-0.11506808+0.2375112j -0.11506808-0.2375112j]
Year 1981-1981, ensemble member slice(1, 97, None) finished
[-0.16591687  0.24248653 -0.2433008  -0.0642193 ]
-------

[[-0.90152954 -0.06908904]
 [-0.85021795 -0.38536194]]
Eigenvalues:[-0.99749092+0.j -0.28940056+0.j]
Year 2004-2004, ensemble member slice(1, 97, None) finished
[-0.90152954 -0.06908904 -0.85021795 -0.38536194]
----------------------------------------
[[-0.05409394  0.21069483]
 [-0.29096325 -0.15749553]]
Eigenvalues:[-0.10579473+0.24213938j -0.10579473-0.24213938j]
[[-0.1529034   0.12464591]
 [-0.47292168 -0.38060739]]
Eigenvalues:[-0.2667554+0.21444225j -0.2667554-0.21444225j]
Year 2005-2005, ensemble member slice(1, 97, None) finished
[-0.1529034   0.12464591 -0.47292168 -0.38060739]
----------------------------------------
[[-0.44479735  0.46425471]
 [-0.72014257  0.08094728]]
Eigenvalues:[-0.18192503+0.51500265j -0.18192503-0.51500265j]
[[-0.68565417  0.47856072]
 [-0.85138669 -0.08756225]]
Eigenvalues:[-0.38660821+0.5639253j -0.38660821-0.5639253j]
Year 2006-2006, ensemble member slice(1, 97, None) finished
[-0.68565417  0.47856072 -0.85138669 -0.08756225]
-----------------------

[[-0.21977529  0.30504448]
 [-0.08343142 -0.16684647]]
Eigenvalues:[-0.19331088+0.1573211j -0.19331088-0.1573211j]
[[-0.3843332   0.4620196 ]
 [-0.03573133 -0.22332164]]
Eigenvalues:[-0.30382742+0.10013689j -0.30382742-0.10013689j]
Year 1973-1973, ensemble member slice(1, 97, None) finished
[-0.3843332   0.4620196  -0.03573133 -0.22332164]
----------------------------------------
[[ 0.02514259  0.11532844]
 [-0.01379426 -0.10111182]]
Eigenvalues:[ 0.01094567+0.j -0.0869149 +0.j]
[[-0.21061344  0.11255309]
 [-0.07081721 -0.11365343]]
Eigenvalues:[-0.16213344+0.07496922j -0.16213344-0.07496922j]
Year 1974-1974, ensemble member slice(1, 97, None) finished
[-0.21061344  0.11255309 -0.07081721 -0.11365343]
----------------------------------------
[[ 0.21983516 -0.10065851]
 [-0.04049234 -0.06624335]]
Eigenvalues:[ 0.23343602+0.j -0.07984421+0.j]
[[-0.00560884 -0.10262693]
 [-0.05133314 -0.10094423]]
Eigenvalues:[ 0.03355878+0.j -0.14011185+0.j]
Year 1975-1975, ensemble member slice(1, 97, N

[[-0.46697486  0.3020186 ]
 [-0.15184242  0.04737394]]
Eigenvalues:[-0.35220634+0.j -0.06739457+0.j]
Year 1996-1996, ensemble member slice(1, 97, None) finished
[-0.46697486  0.3020186  -0.15184242  0.04737394]
----------------------------------------
[[-0.18647532  0.54781894]
 [-0.14671119 -0.10268757]]
Eigenvalues:[-0.14458144+0.28038558j -0.14458144-0.28038558j]
[[-0.20575061  0.58487824]
 [-0.12340268 -0.15135211]]
Eigenvalues:[-0.17855136+0.26727466j -0.17855136-0.26727466j]
Year 1997-1997, ensemble member slice(1, 97, None) finished
[-0.20575061  0.58487824 -0.12340268 -0.15135211]
----------------------------------------
[[-0.45211242  0.2905594 ]
 [-0.11378601 -0.11351255]]
Eigenvalues:[-0.28281249+0.06632592j -0.28281249-0.06632592j]
[[-0.90878146  0.53110054]
 [-0.00583242 -0.17121601]]
Eigenvalues:[-0.9045575 +0.j -0.17543997+0.j]
Year 1998-1998, ensemble member slice(1, 97, None) finished
[-0.90878146  0.53110054 -0.00583242 -0.17121601]
-----------------------------------

[[-0.05715829  0.03610673]
 [-0.0452794  -0.10652677]]
Eigenvalues:[-0.08184253+0.03202467j -0.08184253-0.03202467j]
Year 1969-1969, ensemble member slice(1, 97, None) finished
[-0.05715829  0.03610673 -0.0452794  -0.10652677]
----------------------------------------
[[-0.05430783  0.28823799]
 [ 0.00805906 -0.02402478]]
Eigenvalues:[-0.08968555+0.j  0.01135294+0.j]
[[-0.22612984  0.61556048]
 [ 0.1411109  -0.29384864]]
Eigenvalues:[ 0.03667345+0.j -0.55665193+0.j]
Year 1970-1970, ensemble member slice(1, 97, None) finished
[-0.22612984  0.61556048  0.1411109  -0.29384864]
----------------------------------------
[[ 0.15640525 -0.04711259]
 [-0.00291906 -0.1026624 ]]
Eigenvalues:[ 0.15693501+0.j -0.10319216+0.j]
[[ 0.0988469  -0.16145116]
 [-0.05620349 -0.27603275]]
Eigenvalues:[ 0.12166361+0.j -0.29884946+0.j]
Year 1971-1971, ensemble member slice(1, 97, None) finished
[ 0.0988469  -0.16145116 -0.05620349 -0.27603275]
----------------------------------------
[[-0.08958193  0.31122668]

[[-0.37576485  0.17678019]
 [-0.11106053  0.00260572]]
Eigenvalues:[-0.31369279+0.j -0.05946635+0.j]
Year 1996-1996, ensemble member slice(1, 97, None) finished
[-0.37576485  0.17678019 -0.11106053  0.00260572]
----------------------------------------
[[ 0.00761173  0.34414097]
 [-0.13575039  0.23880039]]
Eigenvalues:[0.12320606+0.18263413j 0.12320606-0.18263413j]
[[ 0.01087676  0.27563614]
 [-0.1194254   0.02042931]]
Eigenvalues:[0.01565304+0.18137018j 0.01565304-0.18137018j]
Year 1997-1997, ensemble member slice(1, 97, None) finished
[ 0.01087676  0.27563614 -0.1194254   0.02042931]
----------------------------------------
[[-0.01097288  0.11099732]
 [-0.51877329  0.23163743]]
Eigenvalues:[0.11033228+0.20704469j 0.11033228-0.20704469j]
[[-0.46925536  0.33869472]
 [-0.43421092  0.18107127]]
Eigenvalues:[-0.14409204+0.20330707j -0.14409204-0.20330707j]
Year 1998-1998, ensemble member slice(1, 97, None) finished
[-0.46925536  0.33869472 -0.43421092  0.18107127]
-------------------------

In [17]:
for s in ('DJF','MAM','JJA','SON'):
    jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_10y_'+s+'_STD', 
                            sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = range(1965,2010), #Anything iterable
                            windowlength = 10, 
                            ensemble =  range(97), #also has to be iterable
                            season = s,
                           )

In [5]:
for s in ('DJF','MAM','JJA','SON'):
    jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_15y_'+s+'_STD', 
                            sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = range(1965,2005), #Anything iterable
                            windowlength = 15, 
                            ensemble =  range(97), #also has to be iterable
                            season = s,
                           )